// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb8-YZnzJucD2NUllWZAEdeaamhQeI9M8',
    appId: '1:182874385983:web:f43f48ddd466aad557d28a',
    messagingSenderId: '182874385983',
    projectId: 'instagram-clone-b9819',
    authDomain: 'instagram-clone-b9819.firebaseapp.com',
    storageBucket: 'instagram-clone-b9819.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBexTn5lxh0HfX7JyleCsHT45VjaWOj_s8',
    appId: '1:182874385983:android:3534ee162377cf8557d28a',
    messagingSenderId: '182874385983',
    projectId: 'instagram-clone-b9819',
    storageBucket: 'instagram-clone-b9819.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0zWZ1BuM9dETeIigdfJG050lv4DIHOSk',
    appId: '1:182874385983:ios:5d611d3e0fde6c1057d28a',
    messagingSenderId: '182874385983',
    projectId: 'instagram-clone-b9819',
    storageBucket: 'instagram-clone-b9819.appspot.com',
    iosClientId: '182874385983-ssnmfodbfa75gr87tp6tmgtm0ra6k07u.apps.googleusercontent.com',
    iosBundleId: 'com.example.igClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0zWZ1BuM9dETeIigdfJG050lv4DIHOSk',
    appId: '1:182874385983:ios:f191d86e926d563e57d28a',
    messagingSenderId: '182874385983',
    projectId: 'instagram-clone-b9819',
    storageBucket: 'instagram-clone-b9819.appspot.com',
    iosClientId: '182874385983-32pjq59lussav1umjj6unoqvnfv7bg3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.igClone.RunnerTests',
  );
}
